name: CI

on:
  - push

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10'
      - name: Install Dependencies
        run: npm ci
      - name: Check Lint
        run: npm run test

  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10'
      - name: Install Dependencies
        run: npm ci
      - name: Build Test
        run: npm run build
