name: Sync
on:
  push:
    branches:
      - master
jobs:
  sync_branch:
    name: Syncing branches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Sync branches
        uses: tibdex/autosquash@v2
        with:
          # We can't use the built-in secrets.GITHUB_TOKEN yet because of this limitation:
          # https://github.community/t5/GitHub-Actions/Triggering-a-new-workflow-from-another-workflow/td-p/31676
          # In the meantime, use a token granting write access on the repo:
          # - a GitHub App token
          #   See https://github.com/marketplace/actions/github-app-token.
          # - a personal access token
          #   See https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line.
          github_token: ${{ secrets.SOSO_TOKEN }}
